version: '3'
services:
  mongodb:
    image: ejjgloria/ejjg-db
    container_name: springboot-mongo
    ports:
     - "23456:23456"
    restart: always
    volumes:
      - $HOME/data/springboot-mongo-data:/data/db
      - $HOME/data/springboot-mongo-bkp:/data/bkp
  app:
    image: ejjgloria/ejjg-app
    container_name: springboot-app
    ports:
     - "8080:8080"
    restart: always
    depends_on:
     - mongodb
